//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLemon
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_request
    {
        public long request_id { get; set; }
        public Nullable<long> parent_id { get; set; }
        public Nullable<long> status_id { get; set; }
        public string desc { get; set; }
    }
}
